name: Delete Deployments

on: [push]
jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true